### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by LinuxBrickie** [seznam/httpmockserver#14]
The code is under MIT licence yet links to libmicrohttpd which is GPL2.1 or later. Am I correct in saying if I use this library it would effectively fall under GPL2.1 or later rather than MIT?

**Comment by che0** [comment]
libmicrohttpd seems to be licensed not under GPL, but rather LGPL (v2.1 or later, per [its website](https://www.gnu.org/software/libmicrohttpd/#license), the same license is also in v0.9.76 package).

**Comment by LinuxBrickie** [comment]
Oh wow, sorry, completely misread it. Thanks.
