### ISSUE TITLE
library doesn't build

### ISSUE THREAD

**Issue by zkSNARK** [seznam/httpmockserver#3]
cmbp:httpmockserver cm$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
cmbp:httpmockserver cm$ https://github.com/seznam/http
cmbp:httpmockserver cm$ git submodule update --init --recursive
Submodule 'external/cpr' (https://github.com/whoshuu/cpr.git) registered for path 'external/cpr'
Submodule 'external/gtest' (https://github.com/google/googletest.git) registered for path 'external/gtest'
Cloning into '/Users/cm/Downloads/httpmockserver/external/cpr'...
Cloning into '/Users/cm/Downloads/httpmockserver/external/gtest'...
Submodule path 'external/cpr': checked out '3d14e61ed247a90a07db26fb107beb3086a035d6'
Submodule 'opt/curl' (https://github.com/whoshuu/curl.git) registered for path 'external/cpr/opt/curl'
Submodule 'opt/googletest' (https://github.com/whoshuu/googletest.git) registered for path 'external/cpr/opt/googletest'
Submodule 'opt/mongoose' (https://github.com/whoshuu/mongoose.git) registered for path 'external/cpr/opt/mongoose'
Cloning into '/Users/cm/Downloads/httpmockserver/external/cpr/opt/curl'...
Cloning into '/Users/cmgoebel/Downloads/httpmockserver/external/cpr/opt/googletest'...
Cloning into '/Users/cmgoebel/Downloads/httpmockserver/external/cpr/opt/mongoose'...
Submodule path 'external/cpr/opt/curl': checked out '3ea76790571c1f7cf1bed34fabffd3cc20ad3dd3'
Submodule path 'external/cpr/opt/googletest': checked out '3be1ef9f1c6139654a7784c53aa833c7a37a3148'
Submodule path 'external/cpr/opt/mongoose': checked out 'df9f7a795e65657017ab302d6367a49fdd4da183'
Submodule path 'external/gtest': checked out '051053054df6d2dbedd5f572ae288f2f82a289b7'
cmbp:httpmockserver cm$ mkdir build and cd build
mkdir: build: File exists
cmbp:httpmockserver cm$ ls
CMakeLists.txt          README.md               build                   cmake                   external                libhttpmockserver.pc.in test
LICENSE.txt             and                     cd                      doc                     include                 src
cmbp:httpmockserver cm$ cd build/
cmbp:build cm$ ls
cmbp:build cm$ cmake ..
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking compiler C++11 support.
-- httpmockserver CMake Options
-- =======================================================
--   USE_ALL_SYSTEM_LIBS: OFF
--   USE_SYSTEM_CPR: OFF
--   USE_SYSTEM_GTEST: OFF
-- =======================================================
-- Could NOT find mhd (missing: MHD_INCLUDE_DIR MHD_LIBRARY)
-- Found CURL: /usr/lib/libcurl.dylib (found version "7.54.0")
-- Checking compiler flags for C++11 support.
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- C++11 is supported.
-- C++ Requests CMake Options
-- =======================================================
--   USE_SYSTEM_CURL: YES
--   BUILD_CPR_TESTS: NO
--   GENERATE_COVERAGE: OFF
--   CPR_CURL_NOSIGNAL: OFF
--   USE_SYSTEM_GTEST: OFF
--   CMAKE_USE_OPENSSL: ON
-- =======================================================
-- Set CURL_FOUND to TRUE.
-- Set CURL_LIBRARIES to /usr/lib/libcurl.dylib.
-- Set CURL_INCLUDE_DIRS to /usr/include.
-- Using CURL_INCLUDE_DIRS: /usr/include.
-- Using CURL_LIBRARIES: /usr/lib/libcurl.dylib.
-- The C compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.10")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MHD_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/src
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
   used as include directory in directory /Users/cm/Downloads/httpmockserver/test
MHD_LIBRARY (ADVANCED)
    linked by target "test-server" in directory /Users/cm/Downloads/httpmockserver/test
    linked by target "test-server" in directory /Users/cm/Downloads/httpmockserver/test

-- Configuring incomplete, errors occurred!

**Comment by johniez** [comment]
`Could NOT find mhd (missing: MHD_INCLUDE_DIR MHD_LIBRARY)`

Do you have libmicrohttpd library (dev package) installed?

**Comment by zkSNARK** [comment]
you are correct.  it wasn't installed properly
