### ISSUE TITLE
a CMake option to to disable building the tests?

### ISSUE THREAD

**Issue by danielab1** [seznam/httpmockserver#8]
hey, I want to use this project but I want to disable the tests cause I don't want to add the CPR and all other test dependencies. is there is a way or just to edit to Cmake?

**Comment by johniez** [comment]
Hi, this is not configurable. Please just comment `add_subdirectory(test)` line in CMakeLists.txt if you are not interested in tests.

**Comment by danielab1** [comment]
but the CMake still forces me to install the CPR lib. and I can't install it cause in my project we using CMake version less than 3.15 as required in the CPR lib.
